version: '3'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:create && rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/kart_racing
      - bundle_path:/bundle
    ports:
      - "3000:3000"
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - BUNDLE_APP_CONFIG=/kart_racing/.bundle

    depends_on:
      - db
volumes:
  bundle_path:
  db:
